=== DomingoFloresOrtega/XML_DAW/Relaciones/relacion4/ejercicio17/Buzon_correos.dtd
<!ELEMENT buzon (carta | paquete)+>
<!ELEMENT carta (remitente, destinatario, direccion)>
<!ELEMENT paquete (remitente, destinatario, direccion, pagado?)>
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT pagado EMPTY>
<!ATTLIST buzon sucursal CDATA #REQUIRED>
<!ATTLIST carta numero ID #REQUIRED>
<!ATTLIST paquete numero ID #REQUIRED>

=== DomingoFloresOrtega/XML_DAW/Relaciones/relacion4/ejercicio16/Buzon_correos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE buzon SYSTEM "Buzon_correos.dtd">

<buzon sucursal="_30">
 <carta numero="_100">
  <remitente>Juan Martinez</remitente>
  <destinatario>Francisco Ramos</destinatario>
  <direccion>Calle Castilla 8, Madrid</direccion>
 </carta>
 
 <paquete numero="_850">
  <remitente>Joaquin Rodriguez</remitente>
  <destinatario>Francisco Gallardo</destinatario>
  <direccion>Calle Martin Martin 7, Huelva</direccion>
  <pagado />
 </paquete>
</buzon>
