<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Libro [
<!ELEMENT Libro (Titulo, Contenido, Copyright)>
<!ATTLIST Libro id CDATA #REQUIRED>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Contenido (Capitulo, Separacion?)+>
<!ELEMENT Capitulo (Tema, Seccion+)>
<!ATTLIST Capitulo materia CDATA #IMPLIED>
<!ELEMENT Tema (#PCDATA)>
<!ELEMENT Seccion (#PCDATA)>
<!ATTLIST Seccion apartados CDATA #REQUIRED dificil CDATA #IMPLIED>
<!ELEMENT Separacion EMPTY>
<!ELEMENT Copyright (#PCDATA)>
]>

<Libro id="DM-1">
  <Titulo>Dos mares</Titulo>
  <Contenido>
   <Capitulo materia="intro">
    <Tema>Introduccion</Tema>
    <Seccion apartados="1" dificil="NO">Los comienzos</Seccion>
   </Capitulo>
   <Separacion />
  </Contenido>
  <Copyright>Editorial Planeta</Copyright>
</Libro>